// Curated list of apps & projects shown on the page.
// Edit freely: stars are a snapshot (update whenever you like),
// `links` accepts anything: App Store, YouTube demo, blog post, etc.
// `slug` powers deep links like https://your.site/#semaphore for social posts.
const PROJECTS = [
  {
    slug: "primoengine",
    name: "PrimoEngine",
    emoji: "🖼️",
    tagline: "Native animated wallpapers for macOS",
    description:
      "Native animated wallpapers for macOS — video, Metal shaders and web — built to respect your battery and GPU. Curated freemium library with a shader/web engine plus AI-generated scenes.",
    category: "Products",
    platforms: ["macOS"],
    tech: ["Swift", "Metal"],
    stars: 1,
    github: "https://github.com/lucianodiisouza/livewallpaper",
    links: [],
    featured: true,
  },
  {
    slug: "lifeboard",
    name: "LifeBoard",
    emoji: "🧩",
    tagline: "Modular, self-hosted personal life dashboard",
    description:
      "A shell-first personal dashboard where every feature is a pluggable module: Thoughts, Tasks, Money, Calendar, Goals, GitHub, File Board and Mood. Universal inbox capture, ⌘K search across modules, and cross-module links (tasks ↔ thoughts). Web-only, single-user, self-hosted for ~$7/mo.",
    category: "Web Apps",
    platforms: ["Web", "Self-hosted"],
    tech: ["TypeScript", "React"],
    stars: 12,
    github: "https://github.com/lucianodiisouza/lifeboard",
    links: [],
    featured: true,
  },
  {
    slug: "conduzir",
    name: "Conduzir",
    emoji: "🎓",
    tagline: "Gestão para autoescolas e instrutores",
    description:
      "Management platform for driving schools and independent instructors: scheduling, students and day-to-day operations in one place. Closed source.",
    category: "Products",
    platforms: ["Web"],
    tech: ["TypeScript"],
    stars: null,
    github: null,
    links: [{ label: "conduzir.online", url: "https://conduzir.online" }],
    featured: true,
  },
  {
    slug: "semaphore",
    name: "Semaphore",
    emoji: "🚦",
    tagline: "Floating traffic light for AI coding agents",
    description:
      "Know at a glance when your AI coding agent is idle, thinking, or writing. Works with Claude Code, Codex, Cursor, Copilot and more, and includes a Stream Deck plugin.",
    category: "Dev Tools",
    platforms: ["macOS"],
    tech: ["Rust"],
    stars: 41,
    github: "https://github.com/lucianodiisouza/semaphore",
    links: [],
    featured: true,
  },
  {
    slug: "detran-questions",
    name: "Teorical Questions DETRAN",
    emoji: "🚗",
    tagline: "Practice app for the Brazilian driving theory exam",
    description:
      "Study and practice real DETRAN theory exam questions before taking the official Brazilian driver's license test.",
    category: "Education",
    platforms: ["Web"],
    tech: ["TypeScript"],
    stars: 67,
    github: "https://github.com/lucianodiisouza/teorical-questions-detran",
    links: [],
    featured: true,
  },
  {
    slug: "recta",
    name: "Recta (self-hosted)",
    emoji: "💸",
    tagline: "Self-hosted personal finance app",
    description:
      "Own your financial data. Recta is a personal finance app you can run on your own server, split into a backend API and a web frontend.",
    category: "Web Apps",
    platforms: ["Web", "Self-hosted"],
    tech: ["TypeScript"],
    stars: 74,
    github: "https://github.com/lucianodiisouza/recta-selfhosted-backend",
    links: [
      { label: "Backend", url: "https://github.com/lucianodiisouza/recta-selfhosted-backend" },
      { label: "Frontend", url: "https://github.com/lucianodiisouza/recta-selfhosted-frontend" },
    ],
    featured: true,
  },
  {
    slug: "primeclip",
    name: "PrimeClip",
    emoji: "🎬",
    tagline: "Local-first, AI-powered video clipping",
    description:
      "Turn long recordings into short clips with AI. Everything runs locally, so your footage never leaves your machine. An open OpusClip alternative.",
    category: "Video & Content",
    platforms: ["Desktop"],
    tech: ["TypeScript"],
    stars: 23,
    github: "https://github.com/lucianodiisouza/PrimeClip",
    links: [],
    featured: true,
  },
  {
    slug: "notchy",
    name: "Notchy",
    emoji: "📜",
    tagline: "A tiny teleprompter that lives in your notch",
    description:
      "A macOS teleprompter tucked into the notch area, so you can read your script while looking straight at the camera.",
    category: "Video & Content",
    platforms: ["macOS"],
    tech: ["Swift"],
    stars: 14,
    github: "https://github.com/lucianodiisouza/notchy-desktop-macos",
    links: [],
    featured: false,
  },
  {
    slug: "camera-man",
    name: "Camera Man",
    emoji: "📷",
    tagline: "Powerful, customizable camera app for macOS",
    description:
      "A camera overlay for content creators recording on macOS. Customize how you appear on screen while recording yourself.",
    category: "Video & Content",
    platforms: ["macOS"],
    tech: ["Swift"],
    stars: 10,
    github: "https://github.com/lucianodiisouza/camera-man-macos",
    links: [],
    featured: false,
  },
  {
    slug: "open-mock",
    name: "Open Mock",
    emoji: "🖼️",
    tagline: "Mockup generator for chat, AI, social & email screenshots",
    description:
      "Generate realistic fake screenshots of chat conversations, AI answers, social posts, stories and emails for demos, tutorials and content.",
    category: "Web Apps",
    platforms: ["Web"],
    tech: ["TypeScript"],
    stars: 9,
    github: "https://github.com/lucianodiisouza/open-mock",
    links: [{ label: "Try it", url: "https://open-mock.vercel.app" }],
    featured: false,
  },
  {
    slug: "interview-algorithms",
    name: "Interview Algorithm Serie",
    emoji: "🧠",
    tagline: "Algorithm interview prep exercises",
    description:
      "A growing collection of algorithm exercises for coding interview preparation, from the interview series on my channels.",
    category: "Education",
    platforms: ["Any"],
    tech: ["JavaScript"],
    stars: 7,
    github: "https://github.com/lucianodiisouza/interview-algorithm-serie",
    links: [],
    featured: false,
  },
  {
    slug: "primo-brutality",
    name: "Primo Brutality UI",
    emoji: "🧱",
    tagline: "Neo-brutalist React Native component library",
    description:
      "@primo-brutality/ui: bold, neo-brutalist components for React Native, with a Storybook preview to browse everything.",
    category: "Dev Tools",
    platforms: ["Mobile"],
    tech: ["TypeScript", "React Native"],
    stars: 5,
    github: "https://github.com/lucianodiisouza/primo-brutality",
    links: [],
    featured: false,
  },
  {
    slug: "primo-ui",
    name: "Primo UI",
    emoji: "🎨",
    tagline: "Design-system library with Stitches + Radix UI",
    description:
      "An (in)complete design system for React built with Stitches and Radix UI, documented in Storybook.",
    category: "Dev Tools",
    platforms: ["Web"],
    tech: ["TypeScript", "React"],
    stars: 4,
    github: "https://github.com/lucianodiisouza/primo-ui",
    links: [{ label: "Storybook", url: "https://lucianodiisouza.github.io/primo-ui/" }],
    featured: false,
  },
  {
    slug: "pokemon-deck",
    name: "Pokemon Deck",
    emoji: "🃏",
    tagline: "A deck of Pokémon cards in the browser",
    description:
      "A React app that renders a browsable deck of Pokémon cards, fetched live from a Pokémon API and styled with styled-components.",
    category: "Experiments",
    platforms: ["Web"],
    tech: ["JavaScript", "React"],
    stars: 1,
    github: "https://github.com/lucianodiisouza/pokemon-deck-fix",
    links: [],
    featured: false,
  },
  {
    slug: "push-web",
    name: "Push Web (AlertWorker)",
    emoji: "🔔",
    tagline: "Staged fake push notifications for recordings",
    description:
      "A static PWA that fires realistic work notifications (chat + calendar) on your iPhone. Block the screen, record the notification center, get the shot. No backend.",
    category: "Video & Content",
    platforms: ["Web", "iOS"],
    tech: ["JavaScript", "PWA"],
    stars: 0,
    github: "https://github.com/lucianodiisouza/push-web",
    links: [{ label: "Try it", url: "https://push-web-nine.vercel.app" }],
    featured: false,
  },
  {
    slug: "anti-antitrampo",
    name: "Anti-Antitrampo",
    emoji: "👀",
    tagline: "Webcam attention monitor that punishes distraction",
    description:
      "Desktop app that tracks your gaze with MediaPipe and spots your phone with YOLOv8. The moment you stop paying attention, it plays a video until you look back.",
    category: "Experiments",
    platforms: ["Desktop"],
    tech: ["Python"],
    stars: 3,
    github: "https://github.com/lucianodiisouza/anti-antitrampo",
    links: [],
    featured: false,
  },
  {
    slug: "esqueletao",
    name: "Esqueletão",
    emoji: "💀",
    tagline: "Skeleton loading components for React Native",
    description:
      "Customizable skeleton loaders with shimmer and pulse animations. New-architecture ready (Fabric/TurboModules), Expo compatible, pure TypeScript.",
    category: "Dev Tools",
    platforms: ["Mobile"],
    tech: ["TypeScript", "React Native"],
    stars: 0,
    github: "https://github.com/lucianodiisouza/esqueletao",
    links: [{ label: "npm", url: "https://www.npmjs.com/package/esqueletao" }],
    featured: false,
  },
  {
    slug: "primotion",
    name: "Primotion",
    emoji: "🌀",
    tagline: "Spring animations for any React element",
    description:
      "Lightweight React animation library: spring physics on any CSS property via hooks, 60fps with requestAnimationFrame, zero dependencies.",
    category: "Dev Tools",
    platforms: ["Web"],
    tech: ["TypeScript", "React"],
    stars: 1,
    github: "https://github.com/lucianodiisouza/primotion",
    links: [{ label: "npm", url: "https://www.npmjs.com/package/primotion" }],
    featured: false,
  },
  {
    slug: "holedeep",
    name: "HoleDeep",
    emoji: "🕳️",
    tagline: "Pomodoro timer with a black hole that enforces your breaks",
    description:
      "A pomodoro timer where breaks are enforced by a black hole that gravitationally lenses your live desktop. Built with Tauri 2, React and WebGL2.",
    category: "Experiments",
    platforms: ["Desktop"],
    tech: ["TypeScript", "Rust"],
    stars: 4,
    github: "https://github.com/lucianodiisouza/holedeep",
    links: [],
    featured: false,
  },
  {
    slug: "icarus",
    name: "Icarus",
    emoji: "🪶",
    tagline: "All-in-one React Native debug & dev tool (WIP)",
    description:
      "One package instead of a pile of separate tools to debug and work on React Native apps — with AI built in, BYOK (bring your own key). Work in progress.",
    category: "Dev Tools",
    platforms: ["Desktop"],
    tech: ["TypeScript", "React Native"],
    stars: 0,
    github: "https://github.com/lucianodiisouza/icarus",
    links: [],
    featured: false,
  },
  {
    slug: "grau",
    name: "Grau (G°)",
    emoji: "🧹",
    tagline: "Free, native macOS storage cleaner (WIP)",
    description:
      "A free, open-source, native macOS utility for cleaning, inspecting and managing your Mac's storage — for people who'd rather not pay for it yearly. Work in progress.",
    category: "Dev Tools",
    platforms: ["macOS"],
    tech: ["Swift"],
    stars: 2,
    github: "https://github.com/lucianodiisouza/grau",
    links: [],
    featured: false,
  },
  {
    slug: "voulum",
    name: "Voulum",
    emoji: "🔊",
    tagline: "Per-app volume control for macOS, from your menu bar",
    description:
      "macOS gives you one system volume, not one per app. Voulum adds the missing mixer: see which app is making sound, jump straight to it, and set each app's volume or mute it independently — built on Core Audio process taps, no kernel extension.",
    category: "Dev Tools",
    platforms: ["macOS"],
    tech: ["Swift"],
    stars: 27,
    github: "https://github.com/lucianodiisouza/voulum",
    links: [],
    featured: false,
  },
];
